#VARIABLE f ABRE EL ARCHIVO datossustituyen COMO SOLO LECTURA (r)
f=open("datossustituyen", 'r')
#ASIGNA VARIABLE lines A FUNCION QUE LEE LINEAS
lines = f.readlines()
#EJECUTA VARIABLE LINES PARA MOSTRAR LAS LINEAS (PARA COMPROBAR QUE LOS DATOS SON CORRECTOS)
lines
#ELIMINA EL SALTO DE LINEA (\n) QUE SE GENERA AUTOMATICAMENTE
lines = [line[:-1] for line in lines]
#EJECUTA VARIABLE LINES PARA MOSTRAR LAS LINEAS (PARA COMPROBAR QUE LOS DATOS SON CORRECTOS)
lines
#CREA VARIABLE asdf PARA EL TEXTO A REEMPLAZAR
asdf = 'TEXTO A REEMPLAZAR'
#CREA VARIABLE asdf CON FUNCION REPLACE Y REEMPLAZA LA LINEA POR EL TEXTO INDICADO
asdf.replace('STRING A REEMPLAZAR', 'STRING POR EL QUE SE REEMPLAZA')
#INDICA QUE, PARA CADA LINEA EN LA FUNCION DECLARADA line (DECLARADA ARRIBA)
#SUSTITUYA POR EL VALOR QUE LE INDIQUEMOS EN TODO EL ARRAY
for line in lines:
 print(asdf.replace('TEXTO A REEMPLAZAR', line))
#CIERRA LA FUNCION
f.close()
